name          'danieldreier-trigger'
version       '0.1.0'
source        'https://github.com/danieldreier/puppet-trigger'
author        'Daniel Dreier'
license       'Apache 2.0'
summary       'Trigger puppet runs on other nodes during catalog application'
description   'Trigger puppet runs on other nodes during catalog application'
project_page  'https://github.com/danieldreier/puppet-trigger'

dependency 'puppetlabs/stdlib'
